# INTRODUCTION TO NUMPY

## 1d Array

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.full(5,12)

array([12, 12, 12, 12, 12])

In [4]:
x = np.array([1,2,34,5,5,6])

In [5]:
x[3] * 5

np.int64(25)

In [6]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])

## MultiDimention

In [37]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
n = np.array([[1,2,3,4],[5,6,7,8,]])

In [39]:
n[0][1]


np.int64(2)

In [40]:
n[0]

array([1, 2, 3, 4])

In [41]:
n[:,1]

array([2, 6])

In [42]:
n[:,1] = [0,1]

In [43]:
n[:,1]

array([0, 1])

## RandomArrays

In [52]:
np.random.rand(2,4)

array([[0.20290687, 0.09253667, 0.26139401, 0.42239359],
       [0.71061627, 0.53999179, 0.24880703, 0.65470943]])

In [56]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])

In [58]:
#Standard normal dist (randN)
np.random.seed(30)
np.random.randn(2,4)

array([[-1.26405266,  1.52790535, -0.97071094,  0.47055962],
       [-0.10069672,  0.30379318, -1.72596243,  1.58509537]])

In [59]:
#Random numbers from 1 to 100
np.random.seed(30)
100 * np.random.rand(2,4)

array([[64.41435361, 38.07484896, 66.30479053, 16.36507261],
       [96.26078137, 34.66618404, 99.17509923, 23.50578956]])

In [61]:
#Random Int
np.random.seed(30)
np.random.randint(low=0 ,high=20 , size=(5,2))

array([[ 5,  5],
       [13, 13],
       [12,  2],
       [17, 14],
       [ 3,  9]])

## Element Wise ops

In [64]:
a = np.array([0,1,2,3,4,5])

In [68]:
a

array([0, 1, 2, 3, 4, 5])

In [67]:
a + 1

array([1, 2, 3, 4, 5, 6])

In [78]:
b = ((a/2)**2)

In [79]:
b

array([0.  , 0.25, 1.  , 2.25, 4.  , 6.25])

In [80]:
a+b

array([ 0.  ,  1.25,  3.  ,  5.25,  8.  , 11.25])

## Comparison Operations

In [70]:
a

array([0, 1, 2, 3, 4, 5])

In [82]:
b

array([0.  , 0.25, 1.  , 2.25, 4.  , 6.25])

In [71]:
a >=2

array([False, False,  True,  True,  True,  True])

In [81]:
a > b

array([False,  True,  True,  True, False, False])

In [85]:
a[a > b],b[a > b]

(array([1, 2, 3]), array([0.25, 1.  , 2.25]))

## Summarizing OPS

In [87]:
a

array([0, 1, 2, 3, 4, 5])

In [88]:
a.min()

np.int64(0)

In [89]:
a.max()

np.int64(5)

In [90]:
a.mean()

np.float64(2.5)

In [91]:
a.std()

np.float64(1.707825127659933)

In [93]:
a.sum()

np.int64(15)