# Linear Algebra


## Vector OPS

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])

In [3]:
#Multiplying a vector
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1,0,0,2])

In [5]:
##Adding a vector
u+v

array([3, 4, 5, 8])

In [6]:
u*v

array([ 2,  0,  0, 12])

## Multiplication

- Vector-Vector
- Vector-Matrix
- Matrix-Matrix

### Vector-Vector (dot Product)

In [7]:
u.shape[0]

4

In [8]:
##Multiply vector and vector and sum it all up

def vector_vector_mult(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range (n):
        result = result + u[i] * v[i]

    return result
        

In [9]:
vector_vector_mult(u,v)

np.float64(14.0)

In [10]:
u.dot(v)

np.int64(14)

### Vector-Matrix (dot Product)

In [11]:
np.random.seed(10)
U = np.random.randint(low= 0,high=10,size=(3,4))
U

array([[9, 4, 0, 1],
       [9, 0, 1, 8],
       [9, 0, 8, 6]])

In [12]:
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range (num_rows):
        result[i] = vector_vector_mult(U[i],v)
    return result

In [13]:
matrix_vector_mult(U,v)

array([11., 25., 21.])

In [14]:
U.dot(v)

array([11, 25, 21])

### Matrix-Matrix (dot Product)

In [15]:
np.random.seed(1)
V = np.array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4]])
V

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4]])

In [16]:
U.shape[1] == V.shape[0]

True

In [17]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows,num_cols))
    
    for i in range (num_cols):
        Vi = V[:,i]
        UVi = matrix_vector_mult(U,Vi)

        result[:,i] = UVi
    return result

In [18]:
matrix_matrix_multiplication(U,V)

array([[ 74.,  74.,  85.],
       [118.,  95., 119.],
       [107., 140., 153.]])

In [19]:
U.dot(V)

array([[ 74,  74,  85],
       [118,  95, 119],
       [107, 140, 153]])

### Identity Matrix (I)

An **identity matrix** is a square matrix with `1`s on the diagonal and `0`s elsewhere:

It acts like `1` in matrix multiplication:

$$
A \\. I = A
$$

Used in ML for:
- Preserving values in transformations
- Matrix inverse checks:  
  $$
  A^{-1} \\. A = I
  $$

In [20]:
I = np.eye(4)

In [21]:
U

array([[9, 4, 0, 1],
       [9, 0, 1, 8],
       [9, 0, 8, 6]])

In [22]:
U.dot(I)

array([[9., 4., 0., 1.],
       [9., 0., 1., 8.],
       [9., 0., 8., 6.]])

 ## Matrix Inverse in Machine Learning

In linear algebra, the **inverse of a matrix** is a powerful concept especially in machine learning, where it's used in solving systems of equations, computing weights in linear regression, and more.

For a square matrix **A**, its inverse is denoted as **A⁻¹**, and it satisfies the following property:

$$
A^{-1} \cdot A = I
$$

Where **I** is the **identity matrix**, which acts like the number 1 in matrix multiplication.


In [23]:
Vs = V[[0,1,2]]

In [24]:
Vs

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [25]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 0.        ,  0.2       ,  0.        ],
       [-0.4       ,  0.28      ,  0.6       ],
       [ 0.46666667, -0.36      , -0.53333333]])

In [27]:
Vs_inv.dot(Vs).astype(int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])